
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mawenhaoteam/WHSpecs.git'
use_frameworks!

platform :ios, '8.0'

target 'Test2_Example' do
  pod 'Test2', :path => '../'
  pod 'WHCategoryKit','0.6.0'
end
